import mongoose, {  Model, Schema } from "mongoose";

const productSchema=new Schema({
    name:{
        type:String,
        required:true,
        trim:true,
    },
    description:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true,
    },
    discountPrice:{
        type:Number
    },
    countInStock:{
        type:Number,
        required:true,
        default:0
    },
    category:{
        type:String,
        required:true,
    },
    brand:{
        type:String,
        required:true,
    },
    sizes:{
        type:[String],
        required:true,
    },
    colors:{
        type:[String],
        required:true,
    },
    collections:{
        type:String,
        required:true
    },
    material:{
        type:String,
    },
    gender:{
        type:String,
        enum:["Men","Women","Unisex"]
    },
    image:{
        type:[String],
    },
    isFeatured:{
        type:Boolean,
        default:false,
    },
    isPublished:{
        type:Boolean,
        default:false,
    },
    rating:{
        type:Number,
        default:0 ,  
    },
    numReviews:{
        type:Number,
        default:0
    },
    tags:[String],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user",
        required:true
    },
    metaTitle:{
        type:String,
    
    },
    metaDescription:{
        type:String
    },
    metaKeyword:{
        type:String,
    },
    dimensions:{
        length:Number,
        width:Number,
        height:Number
    },
    weight:Number
},{timestamps:true})

const productModel=Model("product",productSchema)
export default productModel;